# Generated by Django 5.1 on 2024-08-17 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0002_inmuebles_m2_terreno_inmuebles_numero_est'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmuebles',
            old_name='m2_contruido',
            new_name='m2_construido',
        ),
    ]
